project:
    type: website
    output-dir: docs

website:
    title: "jsqr.org"
    site-url: https://jsqr.org
    description: "Johnathan Jenkins' personal website"
    favicon: favicon.ico
    navbar:
        left:
            - href: index.qmd
              text: Home
            - about.qmd
            - projects.qmd
            - reference.qmd
            - miscellany.qmd
        tools:
            - href: index.xml
              icon: rss
            - href: https://github.com/jsqr/
              icon: github
            - href: https://www.linkedin.com/in/johnathan-jenkins-29806aa8/
              icon: linkedin
            - href: https://mstdn.social/@jsqr
              icon: mastodon
            - href: https://bsky.app/profile/jsqr.bsky.social
              icon: bluesky
            - href: https://pixelfed.social/@jsqr
              icon: camera
    page-footer:
        left: "Â© 2026 Johnathan Jenkins"
        right: "This site does not collect your data."

format:
    html:
        theme:
            - sketchy
        css: styles.css
        toc: true
