project:
  type: website
  output-dir: docs

website:
  title: "jsqr.org"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - reference.qmd
    tools:
      - href: https://github.com/jsqr/
        icon: github
      - href: https://www.linkedin.com/in/johnathan-jenkins-29806aa8/
        icon: linkedin
      - href: https://mstdn.social/@jsqr
        icon: mastodon
      - href: https://bsky.app/profile/jsqr.bsky.social
        icon: bluesky
      - href: https://pixelfed.social/@jsqr
        icon: camera

format:
  html:
    theme:
      - sketchy
    css: styles.css
    toc: true
