project:
  type: website
  output-dir: docs
  post-render: copy_cname.sh

website:
  title: "jsqr.org"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - reference.qmd
    tools:
      - href: https://github.com/jsqr
      - icon: github

format:
  html:
    theme:
      - sketchy
    css: styles.css
    toc: true
